print("How old are you?")
age=input()
print("How tall are you?",end="")
height=input()
print("How much do you weigh?",end="")
weight=input()
print(f"So you're {age} old, {height} tall and {weight} heavy.")
print("Number1:")
a=int(input())
print("Number2:")
b=int(input())
print("Final result:")
c=a+b
print(c)
print("just give your input:")
x = int(input())
print(x)